DROP TABLE IF EXISTS book;

CREATE TABLE book(
    id INTEGER NOT NULL AUTO_INCREMENT,
    title VARCHAR(255) NOT NULL,
    ISBN VARCHAR(255) NOT NULL,
    publicdate VARCHAR(255) NOT NULL,
    price VARCHAR(255) NOT NULL,
    PRIMARY KEY (id)
);