apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookstore
spec:
  selector:
    matchLabels:
      app: bookstore
  replicas: 1
  template:
    metadata:
      labels:
        app: bookstore
    spec:
      containers:
        - name: bookstore
          image: vdhinh/bookstore:latest
          imagePullPolicy: "Always"
          ports:
            - containerPort: 8080
          env:
            - name: RDS_DB_HOST
              value: vdh-mydb.cxljhvpnpb6j.us-east-2.rds.amazonaws.com
            - name: RDS_DB_NAME
              value: admin
            - name: RDS_DB_USERNAME
              value: admin
            - name: RDS_DB_PASSWORD
              value: A32Bh2CQZi
---
apiVersion: v1
kind: Service
metadata:
  name: bookstore-service
spec:
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
  selector:
    app: bookstore
  type: LoadBalancer